apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - name: tcp
    port: 27017
    targetPort: 0
  selector:
    app: mongo
  type: ClusterIP