apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: mongo
  name: mongo
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: mongo
    spec:
      containers:
      - args: []
        image: '{{ .Values.images.mongo }}'
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          name: tcp
      terminationGracePeriodSeconds: 180