apiVersion: v1
data:
  POSTGRES_HOST_AUTH_METHOD: scram-sha-256
  POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: postgres
  name: postgres