apiVersion: v1
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: in_memory
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  HTTP_PORTS: "8080"
  ConnectionStrings__redis: redis:6379
  ConnectionStrings__library: Host=postgres;Port=5432;Username=postgres;Password=fIgYQ0igO01dZYqGqCkHJu;Database=library
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: library-api
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: library-api
  name: library-api